package bg.tuvarna.sit.project.ps.internshipmanagement.service;
import bg.tuvarna.sit.project.ps.internshipmanagement.dto.*;import bg.tuvarna.sit.project.ps.internshipmanagement.dto.application.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.enums.*;import bg.tuvarna.sit.project.ps.internshipmanagement.exception.*;import bg.tuvarna.sit.project.ps.internshipmanagement.mapper.ApplicationMapper;import bg.tuvarna.sit.project.ps.internshipmanagement.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class ApplicationService{
 private final ApplicationRepository apps;private final StudentProfileRepository students;private final InternshipOfferRepository offers;private final CompanyRepository companies;private final CurrentUserService current;private final ApplicationMapper mapper;public ApplicationService(ApplicationRepository a,StudentProfileRepository s,InternshipOfferRepository o,CompanyRepository c,CurrentUserService u,ApplicationMapper m){apps=a;students=s;offers=o;companies=c;current=u;mapper=m;}
 @Transactional public ApplicationDto apply(ApplicationRequest r){StudentProfile p=student();InternshipOffer o=offers.findById(r.getInternshipOfferId()).orElseThrow(()->new ResourceNotFoundException("Internship offer not found"));if(o.getStatus()!=OfferStatus.ACTIVE||o.getDeadline().isBefore(java.time.LocalDate.now()))throw new BadRequestException("Internship offer is not active");if(apps.existsByStudentProfileIdAndInternshipOfferId(p.getId(),o.getId()))throw new DuplicateResourceException("You have already applied to this offer");if(r.getMotivationLetter()==null||r.getMotivationLetter().isBlank())throw new BadRequestException("Motivation letter is required");return mapper.toDto(apps.save(Application.builder().motivationLetter(r.getMotivationLetter()).applicationDate(LocalDateTime.now()).status(ApplicationStatus.PENDING).studentProfile(p).internshipOffer(o).build()));}
 public List<ApplicationDto> studentApps(){return apps.findByStudentProfileId(student().getId()).stream().map(mapper::toDto).toList();}
 public ApplicationDto studentGet(Long id){Application a=apps.findById(id).orElseThrow(()->new ResourceNotFoundException("Application not found"));if(!a.getStudentProfile().getUser().getId().equals(current.get().getId()))throw new ForbiddenActionException("You can view only your own applications");return mapper.toDto(a);}
 public List<ApplicationDto> companyApps(){Company c=company();return apps.findAll().stream().filter(a->a.getInternshipOffer().getCompany().getId().equals(c.getId())).map(mapper::toDto).toList();}
 public List<ApplicationDto> offerApps(Long offerId){InternshipOffer o=offers.findById(offerId).orElseThrow(()->new ResourceNotFoundException("Internship offer not found"));if(!o.getCompany().getUser().getId().equals(current.get().getId()))throw new ForbiddenActionException("You can view applications only for your offers");return apps.findByInternshipOfferId(offerId).stream().map(mapper::toDto).toList();}
 @Transactional public ApplicationDto updateStatus(Long id,ApplicationStatusRequest r){Application a=apps.findById(id).orElseThrow(()->new ResourceNotFoundException("Application not found"));if(!a.getInternshipOffer().getCompany().getUser().getId().equals(current.get().getId()))throw new ForbiddenActionException("You can manage only applications for your offers");if(r.getStatus()==ApplicationStatus.PENDING)throw new BadRequestException("Company cannot set application back to PENDING");a.setStatus(r.getStatus());a.setComment(r.getComment());return mapper.toDto(apps.save(a));}
 private StudentProfile student(){return students.findByUserId(current.get().getId()).orElseThrow(()->new ResourceNotFoundException("Student profile not found"));}private Company company(){return companies.findByUserId(current.get().getId()).orElseThrow(()->new ResourceNotFoundException("Company profile not found"));}
}
