package bg.tuvarna.sit.project.ps.internshipmanagement.service;
import bg.tuvarna.sit.project.ps.internshipmanagement.dto.companyregistration.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.enums.*;import bg.tuvarna.sit.project.ps.internshipmanagement.exception.*;import bg.tuvarna.sit.project.ps.internshipmanagement.mapper.CompanyRegistrationMapper;import bg.tuvarna.sit.project.ps.internshipmanagement.repository.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class CompanyRegistrationService{
 private final CompanyRegistrationRequestRepository requests;private final UserRepository users;private final CompanyRepository companies;private final PasswordEncoder encoder;private final CompanyRegistrationMapper mapper;
 public CompanyRegistrationService(CompanyRegistrationRequestRepository r,UserRepository u,CompanyRepository c,PasswordEncoder e,CompanyRegistrationMapper m){requests=r;users=u;companies=c;encoder=e;mapper=m;}
 @Transactional public CompanyRegistrationResponse create(CompanyRegistrationCreateRequest r){if(users.existsByEmail(r.getRepresentativeEmail())||requests.existsByRepresentativeEmail(r.getRepresentativeEmail()))throw new DuplicateResourceException("Representative email is already used");if(companies.existsByContactEmail(r.getContactEmail())||requests.existsByContactEmail(r.getContactEmail()))throw new DuplicateResourceException("Contact email is already used");var e=mapper.toEntity(r,encoder.encode(r.getPassword()));return mapper.toResponse(requests.save(e),"Company registration request submitted successfully");}
 public List<CompanyRegistrationResponse> pending(){return requests.findByStatus(CompanyRegistrationStatus.PENDING).stream().map(x->mapper.toResponse(x,"Pending company registration request")).toList();}
 public List<CompanyRegistrationResponse> all(){return requests.findAll().stream().map(x->mapper.toResponse(x,"Company registration request")).toList();}
 public CompanyRegistrationResponse get(Long id){return mapper.toResponse(requests.findById(id).orElseThrow(()->new ResourceNotFoundException("Registration request not found")),"Company registration request");}
 @Transactional public CompanyRegistrationResponse approve(Long id,CompanyRegistrationReviewRequest review){var r=requests.findById(id).orElseThrow(()->new ResourceNotFoundException("Registration request not found"));if(r.getStatus()!=CompanyRegistrationStatus.PENDING)throw new BadRequestException("Company registration request is already reviewed");if(users.existsByEmail(r.getRepresentativeEmail()))throw new DuplicateResourceException("Representative email is already used");User u=User.builder().firstName(r.getRepresentativeFirstName()).lastName(r.getRepresentativeLastName()).email(r.getRepresentativeEmail()).password(r.getPasswordHash()).role(Role.COMPANY).authProvider(AuthProvider.LOCAL).enabled(true).build();users.save(u);Company c=companies.save(Company.builder().name(r.getCompanyName()).description(r.getDescription()).website(r.getWebsite()).contactEmail(r.getContactEmail()).city(r.getCity()).user(u).build());r.setStatus(CompanyRegistrationStatus.APPROVED);r.setReviewedAt(LocalDateTime.now());r.setAdminComment(review.getAdminComment());r.setCreatedCompany(c);requests.save(r);return mapper.toResponse(r,"Company approved successfully");}
 @Transactional public CompanyRegistrationResponse reject(Long id,CompanyRegistrationReviewRequest review){var r=requests.findById(id).orElseThrow(()->new ResourceNotFoundException("Registration request not found"));if(r.getStatus()!=CompanyRegistrationStatus.PENDING)throw new BadRequestException("Company registration request is already reviewed");r.setStatus(CompanyRegistrationStatus.REJECTED);r.setReviewedAt(LocalDateTime.now());r.setAdminComment(review.getAdminComment());requests.save(r);return mapper.toResponse(r,"Company registration rejected");}
}
