package bg.tuvarna.sit.project.ps.internshipmanagement.service;
import bg.tuvarna.sit.project.ps.internshipmanagement.dto.*;import bg.tuvarna.sit.project.ps.internshipmanagement.dto.offer.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.*;import bg.tuvarna.sit.project.ps.internshipmanagement.entity.enums.*;import bg.tuvarna.sit.project.ps.internshipmanagement.exception.*;import bg.tuvarna.sit.project.ps.internshipmanagement.mapper.InternshipOfferMapper;import bg.tuvarna.sit.project.ps.internshipmanagement.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDate;import java.util.*;
@Service public class InternshipOfferService{
 private final InternshipOfferRepository offers;private final CompanyRepository companies;private final CurrentUserService current;private final InternshipOfferMapper mapper;public InternshipOfferService(InternshipOfferRepository o,CompanyRepository c,CurrentUserService cu,InternshipOfferMapper m){offers=o;companies=c;current=cu;mapper=m;}
 public List<InternshipOfferDto> search(String location,WorkType type,String skill){List<InternshipOffer> list=offers.findByStatus(OfferStatus.ACTIVE);if(location!=null&&!location.isBlank())list=list.stream().filter(x->x.getLocation().toLowerCase().contains(location.toLowerCase())).toList();if(type!=null)list=list.stream().filter(x->x.getType()==type).toList();if(skill!=null&&!skill.isBlank())list=list.stream().filter(x->x.getRequiredSkills().toLowerCase().contains(skill.toLowerCase())).toList();return list.stream().filter(x->!x.getDeadline().isBefore(LocalDate.now())).map(mapper::toDto).toList();}
 public InternshipOfferDto get(Long id){return mapper.toDto(offers.findById(id).orElseThrow(()->new ResourceNotFoundException("Internship offer not found")));}
 public List<InternshipOfferDto> mine(){Company c=company();return offers.findByCompanyId(c.getId()).stream().map(mapper::toDto).toList();}
 @Transactional public InternshipOfferDto create(InternshipOfferRequest r){Company c=company();return mapper.toDto(offers.save(InternshipOffer.builder().title(r.getTitle()).description(r.getDescription()).requiredSkills(r.getRequiredSkills()).location(r.getLocation()).type(r.getType()).deadline(r.getDeadline()).status(OfferStatus.ACTIVE).company(c).build()));}
 @Transactional public InternshipOfferDto update(Long id,InternshipOfferRequest r){InternshipOffer o=owned(id);o.setTitle(r.getTitle());o.setDescription(r.getDescription());o.setRequiredSkills(r.getRequiredSkills());o.setLocation(r.getLocation());o.setType(r.getType());o.setDeadline(r.getDeadline());if(o.getStatus()==OfferStatus.CLOSED)o.setStatus(OfferStatus.ACTIVE);return mapper.toDto(offers.save(o));}
 @Transactional public InternshipOfferDto close(Long id){InternshipOffer o=owned(id);o.setStatus(OfferStatus.CLOSED);return mapper.toDto(offers.save(o));}
 private Company company(){return companies.findByUserId(current.get().getId()).orElseThrow(()->new ResourceNotFoundException("Company profile not found"));}private InternshipOffer owned(Long id){InternshipOffer o=offers.findById(id).orElseThrow(()->new ResourceNotFoundException("Internship offer not found"));if(!o.getCompany().getUser().getId().equals(current.get().getId()))throw new ForbiddenActionException("You can manage only your own offers");return o;}
}
