import { useState } from "react";
import { apiRequest } from "../api/authApi";
export default function CompanyOfferForm({ offer, onSaved, onCancel }) {
 const [form,setForm]=useState(offer?{title:offer.title,description:offer.description,requiredSkills:offer.requiredSkills,location:offer.location,type:offer.type,deadline:offer.deadline}:{title:'',description:'',requiredSkills:'',location:'',type:'ONSITE',deadline:''});
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 async function submit(event){event.preventDefault();setError('');setBusy(true);try{const data=await apiRequest(offer?`/company/offers/${offer.id}`:'/company/offers',{method:offer?'PUT':'POST',body:JSON.stringify(form)});onSaved(data);}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <section className="detail-panel offer-editor"><h2>{offer?'Edit internship':'Publish an internship'}</h2><p>{offer?'Editing preserves the current status. Use Reopen separately to accept applications again.':'Publishing makes this internship visible to students immediately.'}</p><form className="registration-form" onSubmit={submit}><fieldset disabled={busy}><legend className="sr-only">Internship details</legend><div className="registration-grid">{[['title','Internship title'],['location','Location']].map(([key,label])=><div key={key}><label htmlFor={key}>{label}</label><input id={key} required maxLength={255} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}<div><label htmlFor="type">Work style</label><select id="type" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="ONSITE">On-site</option><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option></select></div><div><label htmlFor="deadline">Application deadline</label><input id="deadline" type="date" required min={today} value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></div></div><label htmlFor="requiredSkills">Required skills (separate with commas)</label><input id="requiredSkills" required maxLength={1000} value={form.requiredSkills} onChange={e=>setForm({...form,requiredSkills:e.target.value})}/><label htmlFor="offerDescription">Internship description</label><textarea id="offerDescription" required maxLength={3000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{error&&<p role="alert">{error}</p>}<div className="account-actions"><button type="submit">{busy?'Saving…':offer?'Save changes':'Publish internship'}</button><button type="button" className="reset-button" onClick={onCancel}>Cancel</button></div></fieldset></form></section>;
}
