import { useEffect, useState } from "react";
import { apiRequest } from "../api/authApi";
export default function AdminCompanyRequestsPage() {
 const [requests,setRequests]=useState([]),[filter,setFilter]=useState('PENDING'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;apiRequest('/admin/company-registration-requests').then(data=>{if(active){setRequests(data);setLoading(false);}}).catch(err=>{if(active){setError(err.message);setLoading(false);}});return()=>{active=false;};},[]);
 return <main><header className="page-header"><span className="eyebrow">ADMINISTRATOR</span><h1>Company registrations</h1><p>Review company and representative details. Approval creates a company account. Rejection must include a reason.</p></header><label htmlFor="requestFilter">Show requests</label><select id="requestFilter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="PENDING">Pending review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="">All requests</option></select>{loading?<p role="status">Loading registrations…</p>:error?<p role="alert">{error}</p>:<div className="review-list">{requests.filter(r=>!filter||r.status===filter).length===0&&<p>No requests in this category.</p>}{requests.filter(r=>!filter||r.status===filter).map(request=><ReviewCard key={request.id} request={request} onReviewed={updated=>setRequests(items=>items.map(item=>item.id===updated.id?updated:item))}/>)}</div>}</main>;
}
function ReviewCard({request,onReviewed}) {
 const [comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 async function review(action){setError('');if(action==='reject'&&!comment.trim()){setError('Enter a reason for rejection.');return;}setBusy(true);try{const result=await apiRequest(`/admin/company-registration-requests/${request.id}/${action}`,{method:'PATCH',body:JSON.stringify({adminComment:comment.trim()})});onReviewed(result);setDone(action==='approve'?'Company approved. The account can now sign in.':'Company rejected. The reason is visible on its status page.');}catch(err){setError(err.message);}finally{setBusy(false);}}
 const safeWebsite=/^https?:\/\//i.test(request.website||'');
 return <article className="detail-panel review-card"><div className="section-heading"><h2>{request.companyName}</h2><span className="badge">{request.status}</span></div><p className="letter">{request.description}</p><dl className="review-details"><dt>City</dt><dd>{request.city}</dd><dt>Website</dt><dd>{safeWebsite?<a className="text-link" href={request.website} target="_blank" rel="noopener noreferrer">{request.website}</a>:request.website||'Not provided'}</dd><dt>Company contact</dt><dd>{request.contactEmail}</dd><dt>Representative</dt><dd>{request.representativeFirstName} {request.representativeLastName}</dd><dt>Sign-in email</dt><dd>{request.representativeEmail}</dd></dl>{request.adminComment&&<p>Feedback: {request.adminComment}</p>}{request.status==='PENDING'&&<><label htmlFor={`review-${request.id}`}>Feedback (required for rejection)</label><textarea id={`review-${request.id}`} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} disabled={busy}/><div className="account-actions"><button className="button" disabled={busy} onClick={()=>review('approve')}>Approve company</button><button className="reset-button" disabled={busy} onClick={()=>review('reject')}>Reject with reason</button></div></>}{error&&<p role="alert">{error}</p>}{done&&<p role="status">{done}</p>}</article>;
}
