import { useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../api/authApi";
const fields=[['companyName','Company name','text'],['city','City','text'],['website','Website (optional)','url'],['contactEmail','Company contact email','email'],['representativeFirstName','Representative first name','text'],['representativeLastName','Representative last name','text'],['representativeEmail','Sign-in email','email']];
export default function CompanyRegistrationPage() {
 const [form,setForm]=useState(Object.fromEntries([...fields.map(([key])=>[key,'']),['description',''],['password',''],['confirm','']]));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(null);
 async function submit(event) {
  event.preventDefault();setError('');if(form.password!==form.confirm){setError('The passwords do not match.');return;}
  setBusy(true);
  try {const {confirm:_,...body}=form;const result=await apiRequest('/company-registration-requests',{method:'POST',body:JSON.stringify(body)});setReceipt(result);setForm({...form,password:'',confirm:''});}
  catch(err){setError(err.message);}finally{setBusy(false);}
 }
 if(receipt){const link=`${window.location.origin}/company-registration/status#${receipt.statusToken}`;return <main><header className="page-header"><span className="eyebrow">REGISTRATION RECEIVED</span><h1>Your request is with us.</h1><p>{receipt.registration.companyName} · Pending review</p></header><section className="empty-panel"><h2>Save your personal status link</h2><p>The administrator will review your details. No email is sent. Keep this private link to check the decision later, including after closing your browser.</p><label htmlFor="statusLink">Your status link</label><input className="status-link" id="statusLink" readOnly value={link} onFocus={e=>e.target.select()}/><Link className="button" to={`/company-registration/status#${receipt.statusToken}`}>Check registration status →</Link><p>You can sign in with your chosen email and password after approval.</p></section></main>;}
 return <main><header className="page-header"><span className="eyebrow">FOR COMPANIES</span><h1>Join the internship community.</h1><p>Tell us about your company and its representative. An administrator will review your request before your account becomes available.</p></header><section className="detail-panel"><form className="registration-form" onSubmit={submit}><fieldset disabled={busy}><legend>Company and representative details</legend><div className="registration-grid">{fields.map(([key,label,type])=><div key={key}><label htmlFor={key}>{label}</label><input id={key} type={type} required={key!=='website'} maxLength={255} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}</div><label htmlFor="description">Company description</label><textarea id="description" required maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="registration-grid"><div><label htmlFor="companyPassword">Password (at least 8 characters)</label><input id="companyPassword" type="password" autoComplete="new-password" required minLength={8} maxLength={64} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div><label htmlFor="companyConfirm">Confirm password</label><input id="companyConfirm" type="password" autoComplete="new-password" required value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></div></div>{error&&<p role="alert">{error}</p>}<button type="submit">{busy?'Submitting…':'Submit registration request'}</button></fieldset></form></section></main>;
}
