import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../api/authApi";
import CompanyOfferForm from "../components/CompanyOfferForm";
import CompanyApplicationReview from "../components/CompanyApplicationReview";
export default function CompanyWorkspace() {
 const [offers,setOffers]=useState([]),[applications,setApplications]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [editor,setEditor]=useState(null),[busy,setBusy]=useState(null),[message,setMessage]=useState(''),[filter,setFilter]=useState('');
 useEffect(()=>{let active=true;Promise.all([apiRequest('/company/offers'),apiRequest('/company/applications')]).then(([o,a])=>{if(active){setOffers(o);setApplications(a);setLoading(false);}}).catch(err=>{if(active){setError(err.message);setLoading(false);}});return()=>{active=false;};},[]);
 function saveOffer(offer){setOffers(items=>items.some(item=>item.id===offer.id)?items.map(item=>item.id===offer.id?offer:item):[offer,...items]);setEditor(null);setMessage(`Internship saved: ${offer.title}. Status: ${offer.status}.`);}
 async function changeStatus(offer,action){if(action==='close'&&!window.confirm(`Close “${offer.title}” to new applications? Existing applications will be kept.`))return;setBusy(offer.id);setError('');setMessage('');try{const result=await apiRequest(`/company/offers/${offer.id}/${action}`,{method:'PATCH'});setOffers(items=>items.map(item=>item.id===result.id?result:item));setMessage(action==='close'?'Internship closed. Existing applications remain available.':'Internship reopened for applications.');}catch(err){setError(err.message);}finally{setBusy(null);}}
 const filtered=applications.filter(a=>!filter||String(a.internshipOfferId)===filter);
 return <main><header className="page-header"><span className="eyebrow">COMPANY WORKSPACE</span><h1>Our offers & applications</h1><p>Publish internships and review the students who applied to your company. Students see your decisions in their own accounts.</p></header>{loading?<p role="status">Loading your workspace…</p>:<>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <section><div className="section-heading"><h2>Our internships</h2><button className="button" disabled={editor!==null||busy!==null} onClick={()=>{setEditor({mode:'create'});setMessage('');}}>Create internship</button></div>
 {editor&&<CompanyOfferForm key={editor.offer?.id||'new'} offer={editor.offer} onSaved={saveOffer} onCancel={()=>setEditor(null)}/>}
 {offers.length===0?<p>No internships yet. Create your first opportunity above.</p>:offers.map(offer=><article className="detail-panel company-offer" key={offer.id}><div className="section-heading"><h3>{offer.title}</h3><span className="badge">{offer.status}</span></div><p>{offer.location} · {offer.type} · Deadline: {offer.deadline}</p>{offer.status==='INACTIVE'&&<p>This internship has been disabled by an administrator.</p>}<div className="account-actions"><Link className="text-link" to={`/student/offers/${offer.id}`}>View details →</Link><button className="reset-button" disabled={editor!==null||busy!==null} onClick={()=>{setEditor({mode:'edit',offer});setMessage('');window.scrollTo({top:0,behavior:'smooth'});}}>Edit internship</button>{offer.status!=='INACTIVE'&&<button className="reset-button" disabled={busy!==null||editor!==null} onClick={()=>changeStatus(offer,offer.status==='ACTIVE'?'close':'reopen')}>{busy===offer.id?'Saving…':offer.status==='ACTIVE'?'Close internship':'Reopen internship'}</button>}<a className="text-link" href="#company-applications" onClick={()=>setFilter(String(offer.id))}>Applications ({applications.filter(a=>a.internshipOfferId===offer.id).length}) →</a></div></article>)}</section>
 <section id="company-applications" className="company-applications"><h2>Applications to our internships</h2><label htmlFor="offerFilter">Filter by internship</label><select id="offerFilter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All our internships</option>{offers.map(offer=><option key={offer.id} value={offer.id}>{offer.title}</option>)}</select>{filtered.length===0?<p>No applications for this selection yet.</p>:<div className="review-list">{filtered.map(application=><CompanyApplicationReview key={application.id} application={application} onSaved={updated=>setApplications(items=>items.map(item=>item.id===updated.id?updated:item))}/>)}</div>}</section>
 </>}</main>;
}
